version: '3.4'

services:
  { { cookiecutter.project_slug } }:
    image: { { cookiecutter.project_slug } }
    container_name: { { cookiecutter.project_slug } }
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080
