language: node_js
addons:
  sonarcloud:
    organization: "gotreasa" # the key of the org you chose at step #3
    token:
      secure: "RVEfFcLiCWNTnxarYhuJgSVaOWT4vdhjcOMp7VAQA2TVbiYaLcbyY/E5/YRjziWa9g9MkuFVbGbqSRQzzTDMaOsVQ9gjV0+goPbEvSLzPgUtOdBRRCCLMYt7TKcYSdbaFavL8yPjCgBPuBzF/srH+8yluinKON7/frC/dbnjtgzHmFboP7bVwSgiCAUZa6PlJ5QiWaMQsepyDvDMyW/zKY4Y7Gwv8TbBgy9/LdmWKdQP+TjNoWQEGT2tUCfOKICWJ1xGz/J39qEpItL9MrRxWA+NkAxjqskJK/ysigTmixfskc0jwEVTH9LP1Q4aDtHLlwPA9kyD8JHgcDIPhESbHyvxhgamaWH8Q6NJzL/uF9qU4Id07UoWQ+u8mCPPJy2qBbr/+xN0yTq6qy6Hp5KXdvCF2uuegQqqo++T7SxesZlDfPwv/mDagSUpXrict2TtpAurEscJHg7Luh4FeC5pq6+sQRdoMVOHN18j+HLsYn0YkDCWoTxN21hJSaGkQh+LqeyHEAbjzWwZwRjMqpOw+cyRIpLZ0LNUMRTzh/sVfY5ZXyy/qbiEKA/f+O/jUjFJOfAPo4QgyI1raW8N+s/TgiXimxs5lWikzmUjvjkAWmMawlRK8i3Y72vm/cz54IU5SL+WMugmfWKsXH4pdPvM1srIa8AgUPtJrFqtCyF8P5o="
stages:
- name: Build
- name: Test
- name: Monitor
jobs:
  include:
  - stage: Build
    name: Snyk vulnerability check
    script:
      snyk test
  - name: SonarCloud check
    script:
    - sonar-scanner
  - language: python
    python: 3.9
    name: Detect secrets in files
    script:
      - pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
      - detect-secrets-hook --baseline .secrets.baseline $(git ls-files)
  - language: node_js
    name: Detect secrets in files
    script:
      commitlint-travis
  - stage: Test
    script:
      - npm test
  - stage: Monitor
    script:
      snyk monitor
env:
  global:
    # SYNK TOKEN
    secure: FIzB3L/Wa3ioDf6rxfTgnslvdRf8++pwth2qtpfcVTJukNlsCVN9Do6xqP0P5pSHrxWy4ySC4J5D8arqqWmiRohNvb/Gqsauvn3HDqTR+emD/IFSrMpfkEvNdi8M4jyFQLuqSZtr4wPkEIzkrjtwtfNo5+6zWVNOIXUEktmcOGQ8RIsccs/DRYrx8JXbZLCzTxs9Jo6eyEPM+qrjN8HMDylo/KOnr1z6xc8z/NtQ6CE/PMn6b6tqxyVfu2e2jjpLC3mrI9fjLZOVyFyIKc852NUEirtGM/gVaeAroqcS6vtJlI6nVudLM+2ZAjPXwtIrLmysdWGRYhx+V/KVFNgRBHTrL/9Ohm4FC32X8yS8m/ceXhqQko7dCBdeyhtd69gZBKCIuVJg1vUXniTq1VJFkH3UKJncuI+P0QJOcwBRwhQf2+rxnUlnpc/jY56oo18USOXeEW3sky66n1/zs7NQIQrNQdr9RIPBmMpzzXvUnuWL49Ix3TQJHBETV6xTpDjEiwFKwix52zlb5CnCHDc2dLTcLBJ6THYhl1vG+kfvlJhRJbDw9GLtgXWV962pTljF+EwvbR1msNOsxxLdWXLwipR2clqmHywweDLrjUBdYU4GrQt27QZDl/P7+vQLhrQEG90eovdC98RzftH2soQOfTIwhaH8vNjUVP8HejaDB8g=
