version: '3.4'

services:
  template-nodejs: # TODO rename
    image: template-nodejs # TODO rename
    container_name: template-nodejs # TODO rename
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080
